### ISSUE TITLE
Upgrade to Camunda 7.13 and Scala 2.13

### ISSUE THREAD

**Issue by pme123** [camunda/dmn-scala#13]
I would like to create a semi-automatic DMN Tester. As a Scala-Developer I would like to use this library and try out Scala 3 - hence I need at least Scala 2.13.

@saig0 In the Forum you mentioned:
> However, I will schedule a new release to update the dependencies :slight_smile:

(see https://forum.camunda.org/t/dmn-scala-plugin-support/19761/6)

I tried it to upgrade it myself - but could not get the tests to work.

Running the existing code did not work at all:

```
[info] Set current project to root (in build file:/Users/mpa/dev/Github/experiments/dmn-scala/)
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/Users/mpa/dev/Github/experiments/dmn-scala/"), "zeebeWorker"):
[error]    org.scala-lang.modules:scala-parser-combinators _2.12, _2.13
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: org.scala-lang.modules:scala-parser-combinators
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
[error] 	at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
```

Can you indicate - if and when you can provide such a release?

**Comment by saig0** [comment]
@pme123 thank you for your interest :balloon: 

I'm working on it whenever I have a bit of time. Currently, I'm really busy. I'll try to do it next week :crossed_fingers:

**Comment by saig0** [comment]
Done: https://github.com/camunda/dmn-scala/releases/tag/1.5.0 :balloon:

**Comment by pme123** [comment]
Where did you publish it? It is not listed here: https://mvnrepository.com/artifact/org.camunda.bpm.extension.dmn.scala/dmn-engine
