### ISSUE TITLE
Error in case of a number with null value

### ISSUE THREAD

**Issue by bhoefman** [camunda/dmn-scala#3]
Hi @saig0 ,

In the following model, Decision_testNumberNull has three rules, transforming a number into a boolean:
1. `>=1` ---> `true`
2. `<1` ---> `false`
3. `null` ---> `null`

I would expect the third rule to be hit in case `"number": null`.
Instead I get 
```
{
    "message": "failed to evaluate expression '>=1':\nexpected Number, Date, Time or Duration but found 'ValNull'"
}
```
The DMN1.1 specification mentions:

> There is no value for notANumber, positiveInfinity, or negativeInfinity. Use null instead.

This is the model:

`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/DMN/20151101/dmn.xsd" xmlns:biodi="http://bpmn.io/schema/dmn/biodi/1.0" id="Definitions_0yik8kn" name="DRD" namespace="http://camunda.org/schema/1.0/dmn">
  <decision id="Decision_testNumberNull" name="Decision_testNumberNull">
    <extensionElements>
      <biodi:bounds x="493" y="154" width="180" height="80" />
    </extensionElements>
    <decisionTable id="decisionTable_1">
      <input id="input_1">
        <inputExpression id="inputExpression_1" typeRef="number">
          <text>number</text>
        </inputExpression>
      </input>
      <output id="output_1" name="result" typeRef="boolean" />
      <rule id="DecisionRule_0yq3enu">
        <inputEntry id="UnaryTests_0mpzyq6">
          <text>&gt;=1</text>
        </inputEntry>
        <outputEntry id="LiteralExpression_1pscgba">
          <text>true</text>
        </outputEntry>
      </rule>
      <rule id="DecisionRule_184h1dc">
        <inputEntry id="UnaryTests_19ptzym">
          <text>&lt;1</text>
        </inputEntry>
        <outputEntry id="LiteralExpression_1o1euap">
          <text>false</text>
        </outputEntry>
      </rule>
      <rule id="DecisionRule_1dbfjb8">
        <inputEntry id="UnaryTests_1ufzcbx">
          <text>null</text>
        </inputEntry>
        <outputEntry id="LiteralExpression_1ytapo9">
          <text>null</text>
        </outputEntry>
      </rule>
    </decisionTable>
  </decision>
</definitions>
`

**Comment by saig0** [comment]
Hi @bhoefman ,

thank you for reaching this out :+1: 

I created a new issue in `feel-scala` camunda/feel-scala#50 because the expressions are evaluated in the FEEL engine.

Do you want to work on a pull request?

**Comment by saig0** [comment]
That is fine :smiley: Your feedback is very valuable.

I will fix the issue when I have time.

**Comment by saig0** [comment]
Fixed with camunda/feel-scala#50

**Comment by bhoefman** [comment]
Hi @saig0 ,
great news! 👍 
since I am currently using the [DMN engine - REST](https://github.com/camunda/dmn-scala/tree/master/engine-rest#how-to-use-it), I was wondering when you were planning a new release that would include this one.

**Comment by saig0** [comment]
I'm planning to do a new release next week or the week after. Is this ok for you or do you need it easier?

**Comment by bhoefman** [comment]
Hi @saig0 

I was just making some changes today and I thought this week would be an ideal timing to also update the model with the null value issue, to simplify the model.
I don't want to put any unnecessary pressure on you, but the earlier the better ;-)

**Comment by saig0** [comment]
@bhoefman , I released a [new version 1.2.1](https://github.com/camunda/dmn-scala/releases/tag/1.2.1) :tada:  Have fun!

**Comment by bhoefman** [comment]
Thanks! 👍 🥇

**Comment by bhoefman** [comment]
Hi @saig0 ,

After some initial tests, it looks like some expressions are handled correctly, but there are still some issues with ranges:
e.g.

> {
>     "message": "failed to evaluate expression ']25..1000000]':\nexpected Number, Date, Time or Duration but found 'ValNull'"
> }

Here are some sample expressions:
- expressions found **ok**:
```
>= 1
< 1
<= 25
>= date("2016-01-01")
```
- expressions found **nok**: 
```
]25..1000000]
[9000..12000000]
```

**Comment by saig0** [comment]
Good catch! I created a new issue: camunda/feel-scala/issues/51.

**Comment by bhoefman** [comment]
@saig0 
I just ran a first test with ]25..1000000] and it was successful 👍 
Thanks!
