### ISSUE TITLE
Output of decision tables generated by Camunda modeler not usable as variables in dmn-scala

### ISSUE THREAD

**Issue by EdCurran** [camunda/dmn-scala#7]
Decision tables generated in Camunda modeler do not behave as I would expect when evaluated with dmn-scala. The output of a decision table is not usable by any DRD elements within the same model that use it as a required decision. Outputs of a decision table are not written to variables in the FEEL engine.

The reason for this is decision table elements generated by Camunda modeler do not include a variable element defining any variables named as outputs of the table. 

An example model created with Camunda modeler 3.1.2 and evaluated with dmn-engine 1.3.1: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/DMN/20151101/dmn.xsd" xmlns:biodi="http://bpmn.io/schema/dmn/biodi/1.0" id="Definitions_0cum8ey" name="DRD" namespace="http://camunda.org/schema/1.0/dmn" exporter="Camunda Modeler" exporterVersion="3.1.2">
  <decision id="decision_dt_output_test" name="decision table test">
    <extensionElements>
      <biodi:bounds x="161" y="266" width="180" height="80" />
    </extensionElements>
    <decisionTable id="decisionTable_1">
      <input id="input_1">
        <inputExpression id="inputExpression_1" typeRef="string">
          <text>true</text>
        </inputExpression>
      </input>
      <output id="output_1" label="My Output Variable" name="myOutputVariable" typeRef="string" />
      <rule id="DecisionRule_0zhf2yo">
        <inputEntry id="UnaryTests_0q0fp8n">
          <text>true</text>
        </inputEntry>
        <outputEntry id="LiteralExpression_0bdx038">
          <text>"my output value"</text>
        </outputEntry>
      </rule>
    </decisionTable>
  </decision>
  <decision id="decision_dt_chaining_test" name="expression test">
    <extensionElements>
      <biodi:bounds x="156" y="80" width="180" height="80" />
      <biodi:edge source="decision_dt_output_test">
        <biodi:waypoints x="254" y="266" />
        <biodi:waypoints x="254" y="160" />
      </biodi:edge>
    </extensionElements>
    <variable id="InformationItem_1mbj8gg" name="expressionOutput" typeRef="string" />
    <informationRequirement>
      <requiredDecision href="#decision_dt_output_test" />
    </informationRequirement>
    <literalExpression id="LiteralExpression_0ycsm8o" expressionLanguage="feel">
      <text>"output variable equals: " + myOutputVariable</text>
    </literalExpression>
  </decision>
</definitions>

```
evaluating that for "decision_dt_chaining_test" will give a warn:
`553 [main] WARN org.camunda.feel.FeelEngine - Suppressed failure: no variable found for name 'myOutputVariable'`

and output of
`NilResult`

I think this is more on the modeler end as it seems decision tables, same as literal expressions (which Camunda modeler does do), should define output variables with the variable element. Can open an issue over there if preferred. Here's a reference table from [https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0017-tableTests/0017-tableTests.dmn](dmn-tck) which uses the variable element. 

Although presumably these models do behave as expected using the Camunda dmn java engine? I haven't tested it. The incompatibility between the modeler and dmn-scala is why I'm submitting this here.

**Comment by EdCurran** [comment]
To add. the above example will work as expected when changed to include a variable element:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/DMN/20151101/dmn.xsd" xmlns:biodi="http://bpmn.io/schema/dmn/biodi/1.0" id="Definitions_0cum8ey" name="DRD" namespace="http://camunda.org/schema/1.0/dmn" exporter="Camunda Modeler" exporterVersion="3.1.2">
  <decision id="decision_dt_output_test" name="decision table test">
    <extensionElements>
      <biodi:bounds x="161" y="266" width="180" height="80" />
    </extensionElements>
    <!--added this-->
    <variable name="myOutputVariable" />
    <!--end-->
    <decisionTable id="decisionTable_1">
      <input id="input_1">
        <inputExpression id="inputExpression_1" typeRef="string">
          <text>true</text>
        </inputExpression>
      </input>
      <output id="output_1" label="My Output Variable" name="myOutputVariable" typeRef="string" />
      <rule id="DecisionRule_0zhf2yo">
        <inputEntry id="UnaryTests_0q0fp8n">
          <text>true</text>
        </inputEntry>
        <outputEntry id="LiteralExpression_0bdx038">
          <text>"my output value"</text>
        </outputEntry>
      </rule>
    </decisionTable>
  </decision>
  <decision id="decision_dt_chaining_test" name="expression test">
    <extensionElements>
      <biodi:bounds x="156" y="80" width="180" height="80" />
      <biodi:edge source="decision_dt_output_test">
        <biodi:waypoints x="254" y="266" />
        <biodi:waypoints x="254" y="160" />
      </biodi:edge>
    </extensionElements>
    <variable id="InformationItem_1mbj8gg" name="expressionOutput" typeRef="string" />
    <informationRequirement>
      <requiredDecision href="#decision_dt_output_test" />
    </informationRequirement>
    <literalExpression id="LiteralExpression_0ycsm8o" expressionLanguage="feel">
      <text>"output variable equals: " + myOutputVariable</text>
    </literalExpression>
  </decision>
</definitions>

```
gets output:
`Result(output variable equals: my output value)`

**Comment by saig0** [comment]
Thank's for raising this up!

You're right. According to the DMN specs, the decision should have a `variable` element. 

However, the DMN engine implements a fallback that uses the decision id instead (https://github.com/camunda/dmn-scala/blob/master/dmn-engine/src/main/scala/org/camunda/dmn/parser/DmnParser.scala#L137). So, it behaves like the Camunda DMN engine. 

In the first DMN example, the result of the decision is stored under the key `decision_dt_output_test` instead of `myOutputVariable`. Maybe, this is unexpected for you because you know how the Camunda DMN engine behaves. But the Camunda DMN engine doesn't follow the specs here. Please have a look at https://github.com/camunda/dmn-scala/wiki/Migrate-from-Camunda-DMN-engine.

Does this make sense for you?
Should I explain more about why or how?

**Comment by EdCurran** [comment]
Ah I see. That does make sense. Missed that wiki entry! 

I don't have any experience with Camunda DMN either, so this is based on initial assumptions on how things would work. And some vague knowledge from skimming over the DMN spec.

So camunda DMN engine does a little shortcut where you can access the output field directly by name without defining it with a variable element?

Whereas DMN scala you can get away without using a variable element by referencing the ID or name of the decision?

I think I just assumed it worked in the camunda DMN engine way because that's what i'd seen in the camunda examples e.g. the dish decider example. Couldn't say which way is better / more spec compliant.

I actually thought including the variable element worked because I named it the same as the name of the output field and the value was somehow mapped over like that. But I see now it's that the output of the decision table as a whole is written to that variable and then can access values as in that wiki entry. So in the absence of an explicit variable element it just defines one with the name/id of the decision table. Makes sense.

Is it possible to emulate the camunda DMN engine behaviour by using multiple variable elements to define a variable for each output? Then you may be able to get parity between dmn-scala and camunda dmn engine in a spec compliant way if you enforce the use of a variable element per output. Or is the only option to use a single variable as the output for the decision table and thus behave as dmn-scala does? 

BTW my initial reaction was to look for a test that showed an example of using the output of a decision table. Couldn't find any in:  https://github.com/camunda/dmn-scala/tree/master/dmn-engine/src/test/resources/decisiontable. 
[this](https://github.com/camunda/dmn-scala/blob/master/dmn-engine/src/test/resources/requirements/discount.dmn) uses the variable approach but couldn't find one that uses the fallback decision name/id approach. Maybe I didn't look hard enough. 

Thanks for the clarification!

**Comment by saig0** [comment]
> So camunda DMN engine does a little shortcut where you can access the output field directly by name without defining it with a variable element?

Correct.

> Whereas DMN scala you can get away without using a variable element by referencing the ID or name of the decision?

Correct. This should help to execute DMN file from the Camunda Modeler.

> the output of the decision table as a whole is written to that variable and then can access values as in that wiki entry. So in the absence of an explicit variable element it just defines one with the name/id of the decision table. 

Correct :+1: 

> Is it possible to emulate the camunda DMN engine behavior by using multiple variable elements to define a variable for each output?

This is not possible by the spec. I could emulate the behavior of Camunda DMN and store the outputs also as variables. It would be good for migration from Camunda DMN. But it is not compliant to the spec and doesn't work for many cases. For example, when the decision table has multiple outputs and a multi-rule hit policy.

**Comment by saig0** [comment]
I close this issue for now. Feel free to reopen it if you have any further questions.
