### ISSUE TITLE
append() and concatenate() results in elements with added variableName

### ISSUE THREAD

**Issue by bhoefman** [camunda/dmn-scala#8]
**Describe the bug**
`append(["a","b","c"],"d")` or `concatenate(["a","b","c"],"d")`, results in `variableName=[{variableName=a},{variableName=b},{variableName=c},{variableName=d}]`, instead of `["a","b","c","d"]`

in case the arguments were passed through as variables, only the appended or concatenated element is affected

**Example1**
decision `simpleAppendedList` with expression `append(["a","b","c"],"d")` results in 
`simpleAppendedList => ObjectValue [value=[{simpleAppendedList=a}, {simpleAppendedList=b}, {simpleAppendedList=c}, {simpleAppendedList=d}], isDeserialized=true, serializationDataFormat=application/x-java-serialized-object, objectTypeName=java.util.ArrayList, serializedValue=352 chars, isTransient=false]`

**Example2**
with input variables
- `initList => ObjectValue [value=[{property2=property2_value1, property1=property1_value1, property3=property3_value1}, {property2=property2_value2, property1=property1_value2, property3=property3_value2}, {property2=property2_value3, property1=property1_value3, property3=property3_value3}], isDeserialized=true, serializationDataFormat=application/x-java-serialized-object, objectTypeName=java.util.ArrayList, serializedValue=564 chars, isTransient=false]`

- `newItem => Value '{"property1" : "property1_value4", "property2" : "property2_value4", "property3" : "property3_value4"}' of type 'PrimitiveValueType[string]', isTransient=false`

decision `appendedList` with expression `append(initList,newItem)` results in 
`appendedList => ObjectValue [value=[{property2=property2_value1, property1=property1_value1, property3=property3_value1}, {property2=property2_value2, property1=property1_value2, property3=property3_value2}, {property2=property2_value3, property1=property1_value3, property3=property3_value3},` **_{appendedList=_**`{"property1" : "property1_value4", "property2" : "property2_value4", "property3" : "property3_value4"}`**_}_**`], isDeserialized=true, serializationDataFormat=application/x-java-serialized-object, objectTypeName=java.util.ArrayList, serializedValue=760 chars, isTransient=false]`

**Environment**
As Camunda BPM process engine plugin?
version: 1.3.1

**Comment by saig0** [comment]
Thank you for reporting! 

I moved the issue to the https://github.com/camunda/dmn-scala repository because it only happens when using the dmn-scala plugin. Using the feel-scala plugin seems to be fine.

**Comment by saig0** [comment]
It is a bug in the plugin. It transforms the evaluation result in the wrong way. Since the result is a list, it assumes that it's from a decision table and split it into multiple `TypeValue`s.

**Comment by bhoefman** [comment]
Hi @saig0 ,

After updating the plugin, a first BAU test - not yet testing append() and concatenate() - revealed the following two issues:
- `[[1,2,3]]` instead of `[1,2,3]`
as a result of the following type of expression
`for x in 0..y
return z+x`
- `a=[{a=[b,c,d]}]` instead of `a=[b,c,d]`
as a result of the following type of filter expression
`x[y=z]`
